//C++ Abstract Syntax Implementation generated by the BNF Converter.
#include <algorithm>
#include <string>
#include <iostream>
#include <vector>
#include "Absyn.H"
namespace TasScript
{
/********************   P    ********************/
P::P(ListLine *p1)
{
  listline_ = p1;

}

P::P(const P & other)
{
  listline_ = other.listline_->clone();

}

P &P::operator=(const P & other)
{
  P tmp(other);
  swap(tmp);
  return *this;
}

void P::swap(P & other)
{
  std::swap(listline_, other.listline_);

}

P::~P()
{
  delete(listline_);

}

void P::accept(Visitor *v)
{
  v->visitP(this);
}

P *P::clone() const
{
  return new P(*this);
}



/********************   LEmpty    ********************/
LEmpty::LEmpty()
{

}

LEmpty::LEmpty(const LEmpty & other)
{

}

LEmpty &LEmpty::operator=(const LEmpty & other)
{
  LEmpty tmp(other);
  swap(tmp);
  return *this;
}

void LEmpty::swap(LEmpty & other)
{

}

LEmpty::~LEmpty()
{

}

void LEmpty::accept(Visitor *v)
{
  v->visitLEmpty(this);
}

LEmpty *LEmpty::clone() const
{
  return new LEmpty(*this);
}



/********************   LCommand    ********************/
LCommand::LCommand(Command *p1)
{
  command_ = p1;

}

LCommand::LCommand(const LCommand & other)
{
  command_ = other.command_->clone();

}

LCommand &LCommand::operator=(const LCommand & other)
{
  LCommand tmp(other);
  swap(tmp);
  return *this;
}

void LCommand::swap(LCommand & other)
{
  std::swap(command_, other.command_);

}

LCommand::~LCommand()
{
  delete(command_);

}

void LCommand::accept(Visitor *v)
{
  v->visitLCommand(this);
}

LCommand *LCommand::clone() const
{
  return new LCommand(*this);
}



/********************   CAddController    ********************/
CAddController::CAddController(Ident p1, ControllerType *p2)
{
  ident_ = p1;
  controllertype_ = p2;

}

CAddController::CAddController(const CAddController & other)
{
  ident_ = other.ident_;
  controllertype_ = other.controllertype_->clone();

}

CAddController &CAddController::operator=(const CAddController & other)
{
  CAddController tmp(other);
  swap(tmp);
  return *this;
}

void CAddController::swap(CAddController & other)
{
  std::swap(ident_, other.ident_);
  std::swap(controllertype_, other.controllertype_);

}

CAddController::~CAddController()
{
  delete(controllertype_);

}

void CAddController::accept(Visitor *v)
{
  v->visitCAddController(this);
}

CAddController *CAddController::clone() const
{
  return new CAddController(*this);
}



/********************   CRemoveController    ********************/
CRemoveController::CRemoveController(Ident p1)
{
  ident_ = p1;

}

CRemoveController::CRemoveController(const CRemoveController & other)
{
  ident_ = other.ident_;

}

CRemoveController &CRemoveController::operator=(const CRemoveController & other)
{
  CRemoveController tmp(other);
  swap(tmp);
  return *this;
}

void CRemoveController::swap(CRemoveController & other)
{
  std::swap(ident_, other.ident_);

}

CRemoveController::~CRemoveController()
{

}

void CRemoveController::accept(Visitor *v)
{
  v->visitCRemoveController(this);
}

CRemoveController *CRemoveController::clone() const
{
  return new CRemoveController(*this);
}



/********************   CSetButton    ********************/
CSetButton::CSetButton(Ident p1, Button *p2)
{
  ident_ = p1;
  button_ = p2;

}

CSetButton::CSetButton(const CSetButton & other)
{
  ident_ = other.ident_;
  button_ = other.button_->clone();

}

CSetButton &CSetButton::operator=(const CSetButton & other)
{
  CSetButton tmp(other);
  swap(tmp);
  return *this;
}

void CSetButton::swap(CSetButton & other)
{
  std::swap(ident_, other.ident_);
  std::swap(button_, other.button_);

}

CSetButton::~CSetButton()
{
  delete(button_);

}

void CSetButton::accept(Visitor *v)
{
  v->visitCSetButton(this);
}

CSetButton *CSetButton::clone() const
{
  return new CSetButton(*this);
}



/********************   CUnsetButton    ********************/
CUnsetButton::CUnsetButton(Ident p1, Button *p2)
{
  ident_ = p1;
  button_ = p2;

}

CUnsetButton::CUnsetButton(const CUnsetButton & other)
{
  ident_ = other.ident_;
  button_ = other.button_->clone();

}

CUnsetButton &CUnsetButton::operator=(const CUnsetButton & other)
{
  CUnsetButton tmp(other);
  swap(tmp);
  return *this;
}

void CUnsetButton::swap(CUnsetButton & other)
{
  std::swap(ident_, other.ident_);
  std::swap(button_, other.button_);

}

CUnsetButton::~CUnsetButton()
{
  delete(button_);

}

void CUnsetButton::accept(Visitor *v)
{
  v->visitCUnsetButton(this);
}

CUnsetButton *CUnsetButton::clone() const
{
  return new CUnsetButton(*this);
}



/********************   CTProController    ********************/
CTProController::CTProController(Color *p1, Color *p2, Color *p3, Color *p4)
{
  color_1 = p1;
  color_2 = p2;
  color_3 = p3;
  color_4 = p4;

}

CTProController::CTProController(const CTProController & other)
{
  color_1 = other.color_1->clone();
  color_2 = other.color_2->clone();
  color_3 = other.color_3->clone();
  color_4 = other.color_4->clone();

}

CTProController &CTProController::operator=(const CTProController & other)
{
  CTProController tmp(other);
  swap(tmp);
  return *this;
}

void CTProController::swap(CTProController & other)
{
  std::swap(color_1, other.color_1);
  std::swap(color_2, other.color_2);
  std::swap(color_3, other.color_3);
  std::swap(color_4, other.color_4);

}

CTProController::~CTProController()
{
  delete(color_1);
  delete(color_2);
  delete(color_3);
  delete(color_4);

}

void CTProController::accept(Visitor *v)
{
  v->visitCTProController(this);
}

CTProController *CTProController::clone() const
{
  return new CTProController(*this);
}



/********************   COLRgb    ********************/
COLRgb::COLRgb(Integer p1, Integer p2, Integer p3)
{
  integer_1 = p1;
  integer_2 = p2;
  integer_3 = p3;

}

COLRgb::COLRgb(const COLRgb & other)
{
  integer_1 = other.integer_1;
  integer_2 = other.integer_2;
  integer_3 = other.integer_3;

}

COLRgb &COLRgb::operator=(const COLRgb & other)
{
  COLRgb tmp(other);
  swap(tmp);
  return *this;
}

void COLRgb::swap(COLRgb & other)
{
  std::swap(integer_1, other.integer_1);
  std::swap(integer_2, other.integer_2);
  std::swap(integer_3, other.integer_3);

}

COLRgb::~COLRgb()
{

}

void COLRgb::accept(Visitor *v)
{
  v->visitCOLRgb(this);
}

COLRgb *COLRgb::clone() const
{
  return new COLRgb(*this);
}



/********************   BButtonA    ********************/
BButtonA::BButtonA()
{

}

BButtonA::BButtonA(const BButtonA & other)
{

}

BButtonA &BButtonA::operator=(const BButtonA & other)
{
  BButtonA tmp(other);
  swap(tmp);
  return *this;
}

void BButtonA::swap(BButtonA & other)
{

}

BButtonA::~BButtonA()
{

}

void BButtonA::accept(Visitor *v)
{
  v->visitBButtonA(this);
}

BButtonA *BButtonA::clone() const
{
  return new BButtonA(*this);
}



/********************   BButtonB    ********************/
BButtonB::BButtonB()
{

}

BButtonB::BButtonB(const BButtonB & other)
{

}

BButtonB &BButtonB::operator=(const BButtonB & other)
{
  BButtonB tmp(other);
  swap(tmp);
  return *this;
}

void BButtonB::swap(BButtonB & other)
{

}

BButtonB::~BButtonB()
{

}

void BButtonB::accept(Visitor *v)
{
  v->visitBButtonB(this);
}

BButtonB *BButtonB::clone() const
{
  return new BButtonB(*this);
}



/********************   BButtonX    ********************/
BButtonX::BButtonX()
{

}

BButtonX::BButtonX(const BButtonX & other)
{

}

BButtonX &BButtonX::operator=(const BButtonX & other)
{
  BButtonX tmp(other);
  swap(tmp);
  return *this;
}

void BButtonX::swap(BButtonX & other)
{

}

BButtonX::~BButtonX()
{

}

void BButtonX::accept(Visitor *v)
{
  v->visitBButtonX(this);
}

BButtonX *BButtonX::clone() const
{
  return new BButtonX(*this);
}



/********************   BButtonY    ********************/
BButtonY::BButtonY()
{

}

BButtonY::BButtonY(const BButtonY & other)
{

}

BButtonY &BButtonY::operator=(const BButtonY & other)
{
  BButtonY tmp(other);
  swap(tmp);
  return *this;
}

void BButtonY::swap(BButtonY & other)
{

}

BButtonY::~BButtonY()
{

}

void BButtonY::accept(Visitor *v)
{
  v->visitBButtonY(this);
}

BButtonY *BButtonY::clone() const
{
  return new BButtonY(*this);
}



/********************   BBumperL    ********************/
BBumperL::BBumperL()
{

}

BBumperL::BBumperL(const BBumperL & other)
{

}

BBumperL &BBumperL::operator=(const BBumperL & other)
{
  BBumperL tmp(other);
  swap(tmp);
  return *this;
}

void BBumperL::swap(BBumperL & other)
{

}

BBumperL::~BBumperL()
{

}

void BBumperL::accept(Visitor *v)
{
  v->visitBBumperL(this);
}

BBumperL *BBumperL::clone() const
{
  return new BBumperL(*this);
}



/********************   BBumperR    ********************/
BBumperR::BBumperR()
{

}

BBumperR::BBumperR(const BBumperR & other)
{

}

BBumperR &BBumperR::operator=(const BBumperR & other)
{
  BBumperR tmp(other);
  swap(tmp);
  return *this;
}

void BBumperR::swap(BBumperR & other)
{

}

BBumperR::~BBumperR()
{

}

void BBumperR::accept(Visitor *v)
{
  v->visitBBumperR(this);
}

BBumperR *BBumperR::clone() const
{
  return new BBumperR(*this);
}



/********************   BBumperSL    ********************/
BBumperSL::BBumperSL()
{

}

BBumperSL::BBumperSL(const BBumperSL & other)
{

}

BBumperSL &BBumperSL::operator=(const BBumperSL & other)
{
  BBumperSL tmp(other);
  swap(tmp);
  return *this;
}

void BBumperSL::swap(BBumperSL & other)
{

}

BBumperSL::~BBumperSL()
{

}

void BBumperSL::accept(Visitor *v)
{
  v->visitBBumperSL(this);
}

BBumperSL *BBumperSL::clone() const
{
  return new BBumperSL(*this);
}



/********************   BBumperSR    ********************/
BBumperSR::BBumperSR()
{

}

BBumperSR::BBumperSR(const BBumperSR & other)
{

}

BBumperSR &BBumperSR::operator=(const BBumperSR & other)
{
  BBumperSR tmp(other);
  swap(tmp);
  return *this;
}

void BBumperSR::swap(BBumperSR & other)
{

}

BBumperSR::~BBumperSR()
{

}

void BBumperSR::accept(Visitor *v)
{
  v->visitBBumperSR(this);
}

BBumperSR *BBumperSR::clone() const
{
  return new BBumperSR(*this);
}



/********************   BTriggerZL    ********************/
BTriggerZL::BTriggerZL()
{

}

BTriggerZL::BTriggerZL(const BTriggerZL & other)
{

}

BTriggerZL &BTriggerZL::operator=(const BTriggerZL & other)
{
  BTriggerZL tmp(other);
  swap(tmp);
  return *this;
}

void BTriggerZL::swap(BTriggerZL & other)
{

}

BTriggerZL::~BTriggerZL()
{

}

void BTriggerZL::accept(Visitor *v)
{
  v->visitBTriggerZL(this);
}

BTriggerZL *BTriggerZL::clone() const
{
  return new BTriggerZL(*this);
}



/********************   BTriggerZR    ********************/
BTriggerZR::BTriggerZR()
{

}

BTriggerZR::BTriggerZR(const BTriggerZR & other)
{

}

BTriggerZR &BTriggerZR::operator=(const BTriggerZR & other)
{
  BTriggerZR tmp(other);
  swap(tmp);
  return *this;
}

void BTriggerZR::swap(BTriggerZR & other)
{

}

BTriggerZR::~BTriggerZR()
{

}

void BTriggerZR::accept(Visitor *v)
{
  v->visitBTriggerZR(this);
}

BTriggerZR *BTriggerZR::clone() const
{
  return new BTriggerZR(*this);
}



/********************   BDpadUp    ********************/
BDpadUp::BDpadUp()
{

}

BDpadUp::BDpadUp(const BDpadUp & other)
{

}

BDpadUp &BDpadUp::operator=(const BDpadUp & other)
{
  BDpadUp tmp(other);
  swap(tmp);
  return *this;
}

void BDpadUp::swap(BDpadUp & other)
{

}

BDpadUp::~BDpadUp()
{

}

void BDpadUp::accept(Visitor *v)
{
  v->visitBDpadUp(this);
}

BDpadUp *BDpadUp::clone() const
{
  return new BDpadUp(*this);
}



/********************   BDpadDown    ********************/
BDpadDown::BDpadDown()
{

}

BDpadDown::BDpadDown(const BDpadDown & other)
{

}

BDpadDown &BDpadDown::operator=(const BDpadDown & other)
{
  BDpadDown tmp(other);
  swap(tmp);
  return *this;
}

void BDpadDown::swap(BDpadDown & other)
{

}

BDpadDown::~BDpadDown()
{

}

void BDpadDown::accept(Visitor *v)
{
  v->visitBDpadDown(this);
}

BDpadDown *BDpadDown::clone() const
{
  return new BDpadDown(*this);
}



/********************   BDpadLeft    ********************/
BDpadLeft::BDpadLeft()
{

}

BDpadLeft::BDpadLeft(const BDpadLeft & other)
{

}

BDpadLeft &BDpadLeft::operator=(const BDpadLeft & other)
{
  BDpadLeft tmp(other);
  swap(tmp);
  return *this;
}

void BDpadLeft::swap(BDpadLeft & other)
{

}

BDpadLeft::~BDpadLeft()
{

}

void BDpadLeft::accept(Visitor *v)
{
  v->visitBDpadLeft(this);
}

BDpadLeft *BDpadLeft::clone() const
{
  return new BDpadLeft(*this);
}



/********************   BDpadRight    ********************/
BDpadRight::BDpadRight()
{

}

BDpadRight::BDpadRight(const BDpadRight & other)
{

}

BDpadRight &BDpadRight::operator=(const BDpadRight & other)
{
  BDpadRight tmp(other);
  swap(tmp);
  return *this;
}

void BDpadRight::swap(BDpadRight & other)
{

}

BDpadRight::~BDpadRight()
{

}

void BDpadRight::accept(Visitor *v)
{
  v->visitBDpadRight(this);
}

BDpadRight *BDpadRight::clone() const
{
  return new BDpadRight(*this);
}



/********************   BStickLeft    ********************/
BStickLeft::BStickLeft()
{

}

BStickLeft::BStickLeft(const BStickLeft & other)
{

}

BStickLeft &BStickLeft::operator=(const BStickLeft & other)
{
  BStickLeft tmp(other);
  swap(tmp);
  return *this;
}

void BStickLeft::swap(BStickLeft & other)
{

}

BStickLeft::~BStickLeft()
{

}

void BStickLeft::accept(Visitor *v)
{
  v->visitBStickLeft(this);
}

BStickLeft *BStickLeft::clone() const
{
  return new BStickLeft(*this);
}



/********************   BStickRight    ********************/
BStickRight::BStickRight()
{

}

BStickRight::BStickRight(const BStickRight & other)
{

}

BStickRight &BStickRight::operator=(const BStickRight & other)
{
  BStickRight tmp(other);
  swap(tmp);
  return *this;
}

void BStickRight::swap(BStickRight & other)
{

}

BStickRight::~BStickRight()
{

}

void BStickRight::accept(Visitor *v)
{
  v->visitBStickRight(this);
}

BStickRight *BStickRight::clone() const
{
  return new BStickRight(*this);
}




/********************   ListLine    ********************/

void ListLine::accept(Visitor *v)
{
  v->visitListLine(this);
}


ListLine *ListLine::clone() const
{
  return new ListLine(*this);
}



}
